# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-Translit-RU
version:      0.03
version_from: lib/Template/Plugin/Translit/RU.pm
installdirs:  site
requires:
    Template::Plugin:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
